default:
  image: ${CI_REGISTRY}/devops/images/usgs/python:3.9
  before_script:
    - bash install.sh 1
    - source ~/miniforge3/etc/profile.d/conda.sh
    - conda activate lsforce

Check formatting and run tests:
  script:
    - black --check .  # Black formatting check
    - isort --check-only .  # isort formatting check
    - pytest --cov-report xml:coverage.xml  # Run tests
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

pages:
  script:
    - mamba install make
    - pushd doc/
    - make html
    - popd
    - mv doc/_build/html/ public/
  artifacts:
    paths:
      - public  # The folder that contains the files to be exposed at the Page URL
