stages:
  - test

Install and test:
  script:
    # Install via the install.sh script
    - source /etc/profile.d/conda.sh
    - bash install.sh 1
    - source activate lsforce
    # Run tests
    - black --skip-string-normalization --check .
    - isort --conda-env lsforce --check-only .
    - pytest --cov-report html:cov_html
  artifacts:
    paths:
      - cov_html
  stage: test
  image: ${DEVOPS_REGISTRY}usgs/conda:latest
  tags:
    - development
