stages:
  - test

Install and test:
  script:
    # Install the lsforce package, its dependencies, and testing packages
    - source /etc/profile.d/conda.sh
    - conda config --add channels conda-forge
    - conda config --set ssl_verify False
    - conda install --yes cartopy notebook obspy pyqt xarray rasterio
    - conda install --yes black isort pytest-cov pytest-mpl
    - pip install --editable .
    # Run tests
    - black --skip-string-normalization --check .
    - isort --conda-env base --check-only .
    - pytest --cov-report html:cov_html
  artifacts:
    paths:
      - cov_html
  stage: test
  image: ${DEVOPS_REGISTRY}usgs/conda:latest
  tags:
    - development
